name: api_app

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  retrofit: ^4.6.0
  get_it: ^9.2.0
  bloc: ^9.2.0
  meta: ^1.16.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5


flutter:
  uses-material-design: true
